### ISSUE TITLE
Questions about enable_materialized_views and enable_transient_replication

### ISSUE THREAD

**Issue by EvonX** [bitnami/bitnami-docker-cassandra#53]
Thanks for providing this useful container! I have a question about two cassandra configs: `enable_materialized_views` and `enable_transient_replication.` It seems the [official document](http://cassandra.apache.org/doc/latest/configuration/cassandra_config_file.html)
does not recommend to enable them in production but the default is enabled:

![image](https://user-images.githubusercontent.com/4555674/56547979-b8392100-6533-11e9-9347-aafdfaef4721.png)

Shall we disable them with bitnami-docker-cassandra image?

Thanks,
-CC

**Comment by miguelaeh** [comment]
Hi @EvonX,
The bitnami image just packages Cassandra so you can use the configuration you need. If this is not recommended to use in production environments in the Cassandra documentation, in the bitnami container is not recommended neither since it packages Cassandra but the configuration do not change.
Since these configs are not supported through environment variables in the bitnami image, you can change the configuration by mounting a config file at the path `/bitnami/cassandra/conf/`. In case you do not provide a config file the default configuration is populated to the `conf` directory, so by default both will be enabled.
